# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-05-19 09:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JXUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=255)),
                ('password', models.CharField(default='', max_length=255)),
                ('gender', models.CharField(choices=[('', 'Unspecified'), ('m', 'Male'), ('f', 'Female'), ('u', 'Unisex')], default='', max_length=1)),
                ('email', models.CharField(default='', max_length=255)),
                ('firstname', models.CharField(default='', max_length=255, null=True)),
                ('lastname', models.CharField(default='', max_length=255, null=True)),
                ('icon', models.CharField(default='', max_length=255, null=True)),
                ('description', models.TextField(default='')),
                ('qq', models.CharField(default='', max_length=12, null=True)),
                ('wechat', models.CharField(default='', max_length=255, null=True)),
                ('city', models.CharField(default='', max_length=255)),
                ('birthday', models.DateField(null=True)),
                ('isblogger', models.BooleanField(default=False)),
                ('isstaff', models.BooleanField(default=False)),
                ('update_datetime', models.DateTimeField(auto_now=True)),
                ('create_datetime', models.DateTimeField(auto_now_add=True)),
                ('removed', models.BooleanField(default=False)),
            ],
        ),
    ]
