# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-05-23 16:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jxuser',
            name='phonenum',
            field=models.CharField(default='', max_length=11),
        ),
        migrations.AlterField(
            model_name='jxuser',
            name='city',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='jxuser',
            name='description',
            field=models.TextField(default='', null=True),
        ),
    ]
